include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
  plugins:
    - riverpod

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # ───────── Architecture & Imports ─────────
    avoid_relative_lib_imports: true
    depend_on_referenced_packages: true
    always_use_package_imports: true

    # ───────── Riverpod & State Discipline ─────────
    prefer_final_locals: true
    prefer_final_fields: true

    # ───────── Async / Dio Safety ─────────
    discarded_futures: false
    unawaited_futures: true
    avoid_void_async: true

    # ───────── Code Quality ─────────
    require_trailing_commas: true
    prefer_const_constructors: true
    avoid_print: true
    only_throw_errors: true
    avoid_catches_without_on_clauses: false
