name: aos_mobile
description: "Africa Online Stores"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # ─────────────────── UI & Design ───────────────────
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3

  # ─────────────────── State Management ───────────────────
  flutter_riverpod: ^3.2.0

  # ─────────────────── Networking ───────────────────
  dio: ^5.9.0

  # ─────────────────── Navigation & Routing ───────────────────
  go_router: ^17.0.1

  # ─────────────────── Local Storage & Persistence ───────────────────
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.4
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.3.0
  image_picker: ^1.2.1
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  riverpod_lint: ^3.0.0-dev.4

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/icons/google.svg
    - assets/icons/apple.svg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

